server:
  port: 8082

spring:
  application:
    name: approval-request-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/erp_approval

employee-service:
  base-url: http://localhost:8081/api

notification-service:
  base-url: http://localhost:8080
grpc:
  server:
    port: 50051
  approval-processing:
    host: localhost
    port: 50052
